In [4]:
import numpy as np

# 1. Inverse of the first matrix
matrix_1 = np.array([[2, 0, 1],
                     [0, 1, 0],
                     [1, 2, 0]])

inverse_matrix_1 = np.linalg.inv(matrix_1)

# Verifying if the inverse is correct by multiplying the matrix with its inverse
identity_matrix = np.dot(matrix_1, inverse_matrix_1)

print("Inverse of the matrix:")
print(inverse_matrix_1)
print("\nVerification (Matrix * Inverse = Identity):")
print(identity_matrix)

# 2. Determinant and rank of matrix A
A = np.array([[4, -3, 7],
              [-1, 6, 3],
              [2, 9, 1]])

det_A = np.linalg.det(A)
rank_A = np.linalg.matrix_rank(A)

print("\nDeterminant of matrix A:", det_A)
print("Rank of matrix A:", rank_A)

Inverse of the matrix:
[[ 0. -2.  1.]
 [ 0.  1.  0.]
 [ 1.  4. -2.]]

Verification (Matrix * Inverse = Identity):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Determinant of matrix A: -251.9999999999998
Rank of matrix A: 3
